#!/usr/bin/env bash
# Auto-generated by dvc-viewer.
# Autoinstalls or updates dvc-viewer if not present or if in CI.

set -euo pipefail

function install_viewer() {
    echo "📦 Installing/Updating dvc-viewer..."
    if command -v uv >/dev/null 2>&1; then
        if [ -n "${VIRTUAL_ENV:-}" ]; then
            uv pip install --quiet --upgrade git+https://github.com/hjamet/dvc-viewer.git
        else
            uv pip install --system --quiet --upgrade git+https://github.com/hjamet/dvc-viewer.git
        fi
    else
        pip install --quiet --upgrade git+https://github.com/hjamet/dvc-viewer.git
    fi
}

if ! command -v dvc-viewer >/dev/null 2>&1; then
    install_viewer
elif [ "${CI:-}" = "true" ] || [ "${DVC_VIEWER_AUTO_UPDATE:-}" = "true" ] || [ "${DVC_VIEWER_AUTO_UPDATE:-}" = "1" ]; then
    install_viewer
fi
